# Generated by Django 2.1 on 2018-08-10 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kamengites',
            new_name='Kamengite',
        ),
    ]
