# Generated by Django 2.1 on 2018-08-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20180810_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamengite',
            name='roll_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='kamengite',
            name='room',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
