# Generated by Django 2.1 on 2018-08-18 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20180811_1420'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kamengite',
        ),
    ]
