# Generated by Django 2.1 on 2018-08-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('phone', models.IntegerField(verbose_name=10)),
                ('designation', models.CharField(max_length=50)),
                ('room', models.CharField(max_length=6)),
                ('img', models.ImageField(upload_to='./logos/')),
            ],
        ),
    ]
