# Generated by Django 2.1 on 2018-08-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_remove_people_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='people',
            name='phone',
            field=models.IntegerField(max_length=14),
        ),
    ]
