# Generated by Django 2.0.1 on 2018-08-29 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20180808_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='People',
        ),
    ]
