# Generated by Django 2.1 on 2018-08-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kamengitesorg',
            name='phone',
        ),
    ]
