# Generated by Django 2.1 on 2018-08-18 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_kamengitesorg_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secy',
            fields=[
                ('secy', models.OneToOneField(on_delete=None, primary_key=True, serialize=False, to='accounts.KamengitesOrg')),
                ('position', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='kamengitesorg',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
