# Generated by Django 2.0.1 on 2018-09-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180830_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='secy',
            name='logos',
            field=models.ImageField(blank=True, upload_to='secy_logos'),
        ),
        migrations.AddField(
            model_name='secy',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
