# Generated by Django 2.0.1 on 2018-08-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_menu', '0002_option_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
