# Generated by Django 2.0.1 on 2018-09-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_menu', '0003_option_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='messdata',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
