# Generated by Django 2.0.1 on 2018-09-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess_menu', '0004_messdata_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messdata',
            name='submitted',
        ),
    ]
