# Generated by Django 2.1 on 2018-08-31 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='post',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
