# Generated by Django 2.1 on 2018-08-18 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_auto_20180815_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='user',
            new_name='u',
        ),
    ]
